name: PROS Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build project
        uses: fishsticks89/pros-build@v1.0